AllCops:
  Include:
    - 'Rakefile'
    - 'lib/**/*'
    - 'bin/**/*'
    - 'spec/**'
  Exclude:
    - 'Gemfile.lock'
    - 'Gemfile'
    - 'gemfiles/**/*'
  TargetRubyVersion: 2.4

Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/ParameterLists:
  Enabled: true
  Max: 5
  CountKeywordArgs: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Style/IfUnlessModifier:
  Enabled: false
  MaxLineLength: 80
