sudo: false
language: ruby
cache: bundler
before_install:
  - rvm get head
  - gem update --system
  - gem install bundler

language: ruby

rvm:
  - jruby-9.0.5.0
  - rbx-3
  - 2.1.9
  - 2.2.4
  - 2.3.1

addons:
  code_climate:
    repo_token: e199bdc9d2cf5ceaa7e46425f118470e43880940098f815a4c972a923102b12b